### ISSUE TITLE
[question]请问如何加载图片

### ISSUE THREAD

**Issue by rexcape** [niuhuan/pica-rust#1]
[`Image`](https://github.com/niuhuan/pica-rust/blob/332dc227ed418e15543e06e78c30edcf9251281c/src/entities.rs#L167) 有 `original_name`，`path` 和 `file_server` 三个属性。无法直接通过拼接 `file_server` 和 `path` 的方式访问。请问应该如何正确加载一张图片

**Comment by niuhuan** [comment]
URL 正确的拼接方式应该是这样

${file_server}/static/${path}

您可以制作浏览器用来观赏, 或者用来学习。 但是不要写爬虫,  或者只下载一些自己需要的部分, 不然接口真的会爆掉, 官方已经发过邮件了, 几乎每个仓库都有收到.

https://github.com/fanyuecheng/Pica/issues/12

**Comment by rexcape** [comment]
> URL 正确的拼接方式应该是这样
> 
> ${file_server}/static/${path}
> 
> 您可以制作浏览器用来观赏, 或者用来学习。 但是不要写爬虫, 或者只下载一些自己需要的部分, 不然接口真的会爆掉, 官方已经发过邮件了, 几乎每个仓库都有收到.
> 
> [fanyuecheng/Pica#12](https://github.com/fanyuecheng/Pica/issues/12)

了解，我只是想搞懂 API 是如何运作的。感谢您的回复
